name: SSH deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

env:
  project_name: power-anly
  service_name: awesomedbt
  service_port: 6000
  nginx_site_path: ${{ secrets.NGINX_SITE_PATH }}/awesomedbt.${{ secrets.DOMAIN }}
  nginx_unit_path: ${{ secrets.NGINX_UNIT_PATH }}/awesomedbt.service
  

jobs:
  # build_and_dbt_test:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - 


  # build_and_service_test:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - 
      
      
  ssh_publish:
    runs-on: ubuntu-20.04
    # conditiom: 
    steps:
      - uses: actions/checkout@v1

      - name: Run ssh checkout
        uses: ./.github/actions/ssh-checkout
        with:
          project-name: ${{ env.project_name }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-user: ${{ secrets.GIHUB_ACTION_USER }}
          git-token: ${{ secrets.GIHUB_ACTION_TOKEN }}

      - name: Run install dbt
        uses: ./.github/actions/ssh-install-dbt
        with:
          project-name: ${{ env.project_name }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run create service unit files
        uses: ./.github/actions/ssh-create-python-unit
        with:
          project-name: ${{ env.project_name }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          unit-service-path: ${{ env.nginx_unit_path }}
          unit-service-exec: uvicorn main:app --host 0.0.0.0 --port ${{ env.service_port }} --app-dir "/root/${{ env.project_name }}/services/api_service"
          unit-service-port: ${{ env.service_port }}
          unit-site-path: ${{ env.nginx_site_path }}
          unit-site-domain: ${{ env.service_name }}.${{ secrets.DOMAIN }}

      - name: Run start service
        uses: ./.github/actions/ssh-start-service
        with:
          project-name: ${{ env.project_name }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          unit-service-name: ${{ secrets.NGINX_SERVICE_NAME }}
          unit-service-env-file: ${{ secrets.AWESOME_DBT_ENV_FILE }}
          dbt-host: ${{ secrets.DBT_HOST }}
          dbt-user: ${{ secrets.DBT_USER }}
          dbt-password: ${{ secrets.DBT_PASSWORD }}